LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY conta_rst IS
	PORT(RST, ENB, CLK: IN STD_LOGIC;
                COUNT: BUFFER INTEGER RANGE 0 TO 7);
END ENTITY;

ARCHITECTURE BEAS OF conta_rst IS
BEGIN

	PROCESS(CLK, RST, ENB)
	BEGIN
		IF RISING_EDGE(CLK) THEN
			IF RST = '1' THEN
				COUNT <= 0;
			ELSIF ENB = '1' THEN
				IF COUNT = 7 THEN
					COUNT <= 0;
				ELSE
					COUNT <= COUNT + 1;
				END IF;
			ELSE
				COUNT <= COUNT;
			END IF;
		END IF;
	END PROCESS;
	
END BEAS;