LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY contador IS
	PORT(CLK,RST: IN STD_LOGIC;
	     VUELTAS: IN INTEGER RANGE 0 TO 3;
        CUENTA,CARRY: BUFFER INTEGER RANGE 0 TO 9 := 0);
END ENTITY;

ARCHITECTURE BEAS OF contador IS
BEGIN

	PROCESS(CLK,VUELTAS,RST)
	BEGIN
		IF RISING_EDGE (CLK) THEN
			IF RST = '1' THEN
				CUENTA <= 0; CARRY <= 0;
			ELSE
				IF CARRY = VUELTAS THEN
					CUENTA <= 0;
				ELSE
					IF CUENTA = 9 THEN
						CUENTA <= 0;
						CARRY <= CARRY + 1;
					ELSE 
						CUENTA <= CUENTA + 1;
					END IF;
			END IF;
				END IF;
		END IF;
	END PROCESS;

END BEAS;
