LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY contaasin IS
	PORT(A: IN STD_LOGIC;
        CUENTA: BUFFER INTEGER RANGE 0 TO 4 := 0);
END ENTITY;

ARCHITECTURE BEAS OF contaasin IS
BEGIN

	PROCESS(A)
	BEGIN
		IF FALLING_EDGE(A) THEN
			IF CUENTA = 4 THEN
				CUENTA <= 0;
			ELSE
				CUENTA <= CUENTA + 1;
			END IF;
		ELSE
			CUENTA <= CUENTA;
		END IF;
	END PROCESS;
	
	
END BEAS;