-- CONTADOR DOS DECADAS
-- M.I. BRYAN E ALVAREZ SERNA
-- 7/02/22


LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY contamod IS
	PORT(CLK: IN STD_LOGIC;
		 D, U: OUT INTEGER RANGE 0 TO 9);
END ENTITY;

ARCHITECTURE BEAS OF contamod IS
SIGNAL CUENTA: INTEGER RANGE 0 TO 99;
BEGIN

	PROCESS(CLK)
	BEGIN
		IF FALLING_EDGE (CLK) THEN
			IF CUENTA = 99 THEN
				CUENTA <= 0;
			ELSE
				CUENTA <= CUENTA + 1;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS(CUENTA)
	BEGIN
		U <= CUENTA MOD 10;
		D <= (CUENTA/10) MOD 10;
	END PROCESS;

END BEAS;