LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY error IS
	GENERIC(N := INTEGER 99);
	PORT(AD, R, XLJ: IN STD_LOGIC_VECTOR(1 DOWNTO 0);
	             DA: OUT STD_LOGIC,
					  Y: OUT INTEGER RANGE 0 TO N);
END ENTITY;

ARCHITECTURE BEAS OF errores IS
SIGNAL X: INTEGER RANGE 0 TO N-1;
BEGIN

	PROCESS(AD,R,XLJ)
		IF FALLING_EDGE(XLJ) THEN
			IF AD = '0' THEN
				IF R = '1' THEN
					X <= N;
				ELSIF X < N+1 THEN
					X = X - 1;
				END IF;
			ELSE
				IF R = '1' THEN
					X <= '0';
				ELSIF X > 0 THEN
					X <= X + 1;
			END IF;
		END ELSE;
	END PROCESS;
	
	PROCESS(AD)
	BEGIN
		IF AD = 1 THEN
			DA <= "1";
		ELSE
			DA <= "0";
	END PROCESS;
	
	PROCESS(X,DA)
	BEGIN	
		IF FALLING_EDGE(XLJ) THEN
			Y <= X;
		END IF,
	END PROCESS;
	

END ARCHITECTURE;