LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY push IS
	PORT(PB, CLK: IN STD_LOGIC;
	        PB_Q: OUT STD_LOGIC);
END ENTITY;

ARCHITECTURE BEAS OF push IS
TYPE ESTADOS IS (INICIO,ENCENDER,RETARDO);
SIGNAL EDO_PRES:ESTADOS;
SIGNAL AUX: INTEGER RANGE 0 TO 100000;
SIGNAL AUX2: INTEGER RANGE 0 TO 24999999;
SIGNAL CLK_1K: STD_LOGIC;
BEGIN


	PROCESS(CLK) -- DIVISOR
	BEGIN 
		IF RISING_EDGE (CLK) THEN
			IF AUX2 = 0 THEN  
				CLK_1K <= NOT CLK_1K;
				AUX2 <= 50; 
			ELSE
				AUX2 <= AUX2 - 1; 
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS(CLK_1K,PB)
	BEGIN
		IF RISING_EDGE(CLK_1K) THEN
			CASE EDO_PRES IS
				WHEN INICIO => PB_Q <= '1';
									IF PB = '0' THEN
										EDO_PRES <= ENCENDER;
									ELSE
										EDO_PRES <= INICIO;
									END IF;
				
				WHEN ENCENDER => PB_Q <= '0';
									  EDO_PRES <= RETARDO;
									  
				WHEN RETARDO => IF AUX = 100000 THEN
										 AUX <= 0;
										 EDO_PRES <= INICIO;
									 ELSE
										 AUX <= AUX + 1;
									 END IF;
			END CASE;
		END IF;
	END PROCESS;
	
END BEAS;