-- MEMORIA ROM COMO LOOK-UP TABLE PARA GENERAR UNA SENOIDAL
-- M.I. BRYAN EMMANUEL ALVAREZ SERNA

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY rom IS 
	GENERIC(DATOS: INTEGER:= 10; -- NÚMERO DE DATOS QUE SE VAN A GUARDAR
	     AMPLITUD: INTEGER := 255); -- AMPLITUD DE LA SEÑAL EN BITS (2^n)-1
	PORT(DIR: IN INTEGER RANGE 0 TO DATOS-1;
	     SAL: OUT INTEGER RANGE 0 TO AMPLITUD);
END ENTITY;

ARCHITECTURE BEAS OF rom IS 
TYPE MEMORY IS ARRAY(0 TO DATOS-1) OF INTEGER RANGE 0 TO AMPLITUD;
CONSTANT ROM: MEMORY := (128,202,249,249,202,128,53,6,6,53); -- DATOS CALCULADOS

BEGIN

	SAL <= ROM(DIR);

END BEAS;