LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY sqr IS
PORT(CLK, RST, VIDEO: IN STD_LOGIC; -- RELOJ DE 25 MHz (PLL)
	  HPOS: IN INTEGER RANGE 0 TO 799;
	  VPOS: IN INTEGER RANGE 0 TO 524;-- SALIDAS V y H
	   RGB: OUT STD_LOGIC_VECTOR(2 DOWNTO 0)); -- SALIDA RGB
END sqr;

ARCHITECTURE BEAS OF sqr IS
BEGIN

	PROCESS(CLK, RST, HPOS, VPOS, VIDEO) -- PROCESO PARA COLOREAR LOS PIXELES
	BEGIN
		IF RST = '1' THEN
			RGB <= "000";
		ELSIF FALLING_EDGE(CLK) THEN
			IF VIDEO = '1' THEN
				IF (HPOS >= 280 AND HPOS <= 360) AND (VPOS >= 200 AND VPOS <= 280) THEN
					RGB <= "100";
				ELSE
					RGB <= "000";
				END IF;
			END IF;
		END IF;
	END PROCESS;
	
END BEAS;
