LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY sqr IS
PORT(CLK, RST, VIDEO: IN STD_LOGIC; -- RELOJ DE 25 MHz (PLL)
	  HPOS: IN INTEGER RANGE 0 TO 799;
	  VPOS: IN INTEGER RANGE 0 TO 524;-- SALIDAS V y H
	  R, G, B: OUT STD_LOGIC_VECTOR(3 DOWNTO 0)); -- SALIDA R,G y B
END sqr;

ARCHITECTURE BEAS OF sqr IS
BEGIN

	PROCESS(CLK, RST, HPOS, VPOS, VIDEO) -- PROCESO PARA COLOREAR LOS PIXELES
	BEGIN
		IF RST = '1' THEN
			R <= "0000"; G <= "0000"; B <= "0000";
		ELSIF FALLING_EDGE(CLK) THEN
			IF VIDEO = '1' THEN
				IF (HPOS >= 100 AND HPOS <= 400) AND (VPOS >= 50 AND VPOS <= 150) THEN
					R <= "0000"; G <= "0000"; B <= "1111";
				ELSIF (HPOS >= 150 AND HPOS <= 300) AND (VPOS >= 150 AND VPOS <= 380) THEN
					R <= "0000"; G <= "1111"; B <= "0000";
				ELSE
					R <= "1111"; G <= "0000"; B <= "0000";
				END IF;
			END IF;
		END IF;
	END PROCESS;
	
END BEAS;