-- UART TX 
-- M.I. BRYAN EMMANUEL ALVAREZ SERNA

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY uart_tx IS
	PORT(CLK: IN STD_LOGIC;
		  TX_OUT: OUT STD_LOGIC;
		  BUSY: IN STD_LOGIC; -- INICIA COMUNICACION
		  SW: IN INTEGER RANGE 0 TO 3);
END uart_tx;

ARCHITECTURE BEAS OF uart_tx IS
SIGNAL START: STD_LOGIC;
SIGNAL PRESCL: INTEGER RANGE 0 TO 434 := 0; -- BAUDAJE = 50MHz/PRESCL
SIGNAL INDEX: INTEGER RANGE 0 TO 9 := 0; -- SELECCIONA QUE BIT SE ENVIA
SIGNAL DATA_FRAME: STD_LOGIC_VECTOR(9 DOWNTO 0) ; -- VECTOR DE 8 BITS DE DATOS, BIT DE START Y BIT DE STOP
SIGNAL TX_FLAG: STD_LOGIC := '0';
SIGNAL DATA: STD_LOGIC_VECTOR(7 DOWNTO 0) := (OTHERS => '0'); -- DATO DE 8 BITS
SIGNAL HEX_DATA: STD_LOGIC_VECTOR(7 DOWNTO 0) := (OTHERS => '0');
SIGNAL PLACE: INTEGER RANGE 0 TO 1; -- TAMAÑO DE ARRAY_TX
SIGNAL DELAY: INTEGER := 10000; -- RETARDO ENTRE DATOS
SIGNAL CONTA: INTEGER := 0;
-----------------------------------------------------------------------------------------
TYPE ARRAY_TX IS ARRAY (0 TO 1) OF STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL ASC_DATA : ARRAY_TX := (X"30", X"0A"); -- X0A SALTO DE LINEA

BEGIN

	PROCESS(CLK, BUSY)
	BEGIN
		ASC_DATA(0) <= HEX_DATA; -- PONGO EL DATO QUE ASIGNO
		IF BUSY = '1' THEN
			IF FALLING_EDGE(CLK) THEN
				IF CONTA = DELAY THEN
					CONTA <= 0;
					START <= '1';
					DATA <= ASC_DATA(PLACE);
					IF PLACE = 1 THEN
						PLACE <= 0;
					ELSE
						PLACE <= PLACE + 1;
					END IF;
				ELSE
					CONTA <= CONTA + 1;
					START <= '0';
				END IF;
			END IF;
		END IF;
	END PROCESS;

	PROCESS(CLK)
	BEGIN
		IF RISING_EDGE(CLK) THEN
			IF (TX_FLAG = '0' AND START = '1') THEN 
				TX_FLAG <= '1';
				DATA_FRAME(0) <= '0'; -- BIT DE START
				DATA_FRAME(9) <= '1'; -- BIT DE STOP				
				DATA_FRAME(8 DOWNTO 1) <= DATA; -- 8 BITS (DATOS)
			END IF;
			
			IF TX_FLAG = '1' THEN 
				IF PRESCL < 433 THEN
					PRESCL <= PRESCL + 1;
				ELSE
					PRESCL <= 0;
				END IF;
				IF PRESCL = 217 THEN -- (434/2)
					TX_OUT <= DATA_FRAME (INDEX);
					IF INDEX < 9 THEN
						INDEX <= INDEX + 1;
					ELSE
						TX_FLAG <= '0';
						INDEX <= 0;
					END IF;
				END IF;
			END IF;
		END IF;		
	END PROCESS;
	
	WITH (SW) SELECT -- MUX ASCII (HEX)
		HEX_DATA <= X"41" WHEN 0,
						X"42" WHEN 1,
						X"43" WHEN 2,
						X"44" WHEN 3,
						X"23" WHEN OTHERS;
		

END BEAS;