--==============================================================================
-- 	      CÓDIGO VHDL PARA DESPLIEGUE VGA CON MOVIMIENTO							--
-- 					  M.I. BRYAN EMMANUEL ALVAREZ SERNA									--
-- =============================================================================

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY vga_mov IS
PORT(CLK: IN STD_LOGIC;
	  HSYNC, VSYNC: OUT STD_LOGIC;
	  U,D,L,R: IN STD_LOGIC; -- ENTRADAS PARA MOVER UP, DOWN, LEFT Y RIGHT RESPECTIVAMENTE
	  R, G,B: OUT STD_LOGIC_VECTOR(3 DOWNTO 0)); -- SALIDAS PARA TARJETA DE-10 LITE
END vga_mov;

ARCHITECTURE BEAS OF vga_mov IS
-- VALORES PARA MONITOR DE 640X480
CONSTANT HD: INTEGER := 639; -- PANTALLA HORIZONTAL (640)
CONSTANT VD: INTEGER := 479; -- PANTALLA VERTICAL (480)

CONSTANT HFP: INTEGER := 16; -- BORDE DERECHO (FRONT PORCH)
CONSTANT HSP: INTEGER := 96; -- SINCRONIZACION
CONSTANT HBP: INTEGER := 48; -- BORDE IZQUIERDO (BACK PORCH)

CONSTANT VFP: INTEGER := 10; -- BORDE DERECHO (FRONT PORCH)
CONSTANT VSP: INTEGER := 2; --  SINCRONIZACION
CONSTANT VBP: INTEGER := 33; -- BORDE IZQUIERDO (BACK PORCH)

SIGNAL HPOS: INTEGER := 0; -- BARRIDO HORIZONTAL
SIGNAL VPOS: INTEGER := 0; --  BARRIDO VERTICAL

SIGNAL VIDEO: STD_LOGIC := '0'; -- ACTIVAION DE SALIDA DE VIDEO
SIGNAL RST: STD_LOGIC;

SIGNAL X1: INTEGER RANGE 0 TO 640 := 10; -- VALOR DE HPOS (IZQ)
SIGNAL X2: INTEGER RANGE 0 TO 640 := 600; -- VALOR DE HPOS (DER)
SIGNAL Y1: INTEGER RANGE 0 TO 480 := 10; -- VALOR DE VPOS (ARRIBA)
SIGNAL Y2: INTEGER RANGE 0 TO 480 := 400; -- VALOR DE VPOS (ABAJO)
SIGNAL CLK_ASM : STD_LOGIC;

------------------------ CARTA ASM PARA CONTADOR -------------------------
TYPE EDOS IS (INICIO, IZQ, DER, ARR, ABA, RETARDO);
SIGNAL PRES: EDOS := INICIO;
SIGNAL RET: INTEGER RANGE 0 TO 100000 := 0;
SIGNAL AUX: INTEGER RANGE 0 TO 50;

BEGIN

	RST <= '0';

	PROCESS(CLK, RST) -- CONTADOR HORIZONTAL
	BEGIN
		IF RST = '1' THEN
			HPOS <= 0;
			ELSIF RISING_EDGE (CLK) THEN
				IF HPOS = (HD + HFP + HSP + HBP) THEN
					HPOS <= 0;
				ELSE
					HPOS <= HPOS + 1;
				END IF;
			END IF;		
	END PROCESS;
	
	PROCESS(CLK, RST, HPOS) -- CONTADOR VERTICAL
	BEGIN
		IF RST = '1' THEN
			VPOS <= 0;
			ELSIF RISING_EDGE (CLK) THEN
				IF HPOS = (HD + HFP + HSP + HBP) THEN
					IF VPOS = (VD + VFP + VSP + VBP) THEN
						VPOS <= 0;
					ELSE
						VPOS <= VPOS + 1;
					END IF;
				END IF;	
			END IF;
	END PROCESS;
	
	PROCESS(CLK, RST, HPOS) -- SINCRONIZACION HORIZONTAL
	BEGIN
		IF RST = '1' THEN
			HSYNC <= '0';
		ELSIF FALLING_EDGE(CLK) THEN
			IF HPOS <= (HD + HFP) OR HPOS > (HD + HFP + HSP) THEN
				HSYNC <= '1';
			ELSE
				HSYNC <= '0';
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS(CLK, RST, VPOS) -- SINCRONIZACION VERTICAL
	BEGIN
		IF RST = '1' THEN
			VSYNC <= '0';
		ELSIF FALLING_EDGE(CLK) THEN
			IF VPOS <= (VD + VFP) OR VPOS > (VD + VFP + VSP) THEN
				VSYNC <= '1';
			ELSE
				VSYNC <= '0';
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS(CLK, RST, HPOS, VPOS) -- SALIDA DE VIDEO
	BEGIN
		IF RST = '1' THEN
			VIDEO <= '0';
		ELSIF FALLING_EDGE(CLK) THEN
			IF HPOS <= HD AND VPOS <= VD THEN
				VIDEO <= '1';
			ELSE
				VIDEO <= '0';
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS(CLK)
	BEGIN
		IF RISING_EDGE(CLK) THEN
			IF AUX = 0 THEN
				CLK_ASM <= NOT CLK_ASM;
				AUX <= 50;
			ELSE
				AUX <= AUX - 1;
			END IF;
		END IF;
	END PROCESS;
	
	PROCESS(CLK_ASM, U, D, L, R)
	BEGIN
		IF RISING_EDGE(CLK_ASM) THEN
			CASE PRES IS
				WHEN INICIO => IF U = '0' THEN
										PRES <= ARR;
									ELSIF D = '0' THEN
										PRES <= ABA;
									ELSIF L = '0' THEN
										PRES <= IZQ;
									ELSIF R = '0' THEN
										PRES <= DER;
									ELSE
										PRES <= INICIO;
									END IF;
									
				WHEN DER => X1 <= X1 + 10; X2 <= X2 + 10;
							 PRES <= RETARDO;
							 
				WHEN IZQ => X1 <= X1 - 10; X2 <= X2 - 10;
							 PRES <= RETARDO;		
						
				WHEN ARR => Y1 <= Y1 + 10; Y2 <= Y2 + 10;
							 PRES <= RETARDO;
				
				WHEN ABA => Y1 <= Y1 - 10; Y2 <= Y2 - 10;
							 PRES <= RETARDO;
							
				WHEN RETARDO => IF RET = 100000 THEN
										 RET <= 0;
										 PRES <= INICIO;
									 ELSE
										 RET <= RET + 1;
									 END IF;
			END CASE;
		END IF;
	END PROCESS;
	
	
	
	-- PROCESO VALIDO PARA DE-10 LITE
	PROCESS(CLK, RST, HPOS, VPOS, VIDEO) -- PROCESO PARA COLOREAR LOS PIXELES
	BEGIN
		IF RST = '1' THEN
			R <= "0000";
   		G <= "0000";
			B <= "0000";
		ELSIF FALLING_EDGE(CLK) THEN
			IF VIDEO = '1' THEN
				IF (HPOS >= X1 AND HPOS <= X2) AND (VPOS >= Y1 AND VPOS <= Y2) THEN
					R <= "1111";
   				G <= "0000";
					B <= "0000";
					ELSE
						R <= "0000";
   					G <= "0000";
						B <= "0000";
					END IF;
				ELSE
					R <= "0000";
   				G <= "0000";
					B <= "0000";
				END IF;
			END IF;
	END PROCESS;

END BEAS;