LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY principal IS
		PORT(CLK,DEC,INC: IN STD_LOGIC;
			       CUENTA: OUT INTEGER RANGE 0 TO 9);
END ENTITY;

ARCHITECTURE BEAS OF principal IS

COMPONENT divisor
	   GENERIC(FREC: INTEGER := 0);
		PORT(CLK_MST: IN STD_LOGIC;
			      CLK: OUT STD_LOGIC);
END COMPONENT;

COMPONENT asm
		PORT(INC,DEC,CLK: IN STD_LOGIC;
	             CUENTA: BUFFER INTEGER RANGE 0 TO 9);
END COMPONENT;

SIGNAL DIV_C: STD_LOGIC;

BEGIN

	U1: divisor GENERIC MAP (FREC => 50) PORT MAP(CLK, DIV_C);
	U2: asm PORT MAP (INC,DEC,DIV_C, CUENTA);

END;