LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY conta IS
	PORT(RST,CLK: IN STD_LOGIC;
		  CUENTA: BUFFER INTEGER RANGE 0 TO 9);
END ENTITY;

ARCHITECTURE BEAS OF conta IS
BEGIN

	PROCESS(RST,CLK)
	BEGIN
		IF RISING_EDGE (CLK) THEN
			IF RST = '1' THEN
				CUENTA <= 0;
			ELSIF CUENTA = 9 THEN
				CUENTA <= 0;
			ELSE 
				CUENTA <= CUENTA + 1;
			END IF;
		END IF;
	END PROCESS;

END BEAS;
