LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY colraw IS
	PORT(CUENTA: IN STD_LOGIC_VECTOR(0 TO 3);
	       FIL: IN STD_LOGIC_VECTOR(0 TO 3);
			 COL: OUT STD_LOGIC_VECTOR(0 TO 3);
			 HAB: OUT STD_LOGIC);
END colraw;

ARCHITECTURE BEAS OF colraw IS
BEGIN

	WITH CUENTA(0 TO 1) SELECT
		COL <= "1110" WHEN "00",
		       "1101" WHEN "01",
				 "1011" WHEN "10",
				 "0111" WHEN "11";
				 
				 
	WITH CUENTA(2 TO 3) SELECT
		HAB <= NOT FIL(0) WHEN "00",
				 NOT FIL(1) WHEN "01",
				 NOT FIL(2) WHEN "10",
				 NOT FIL(3) WHEN "11";
		
		
		

END BEAS; 