LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY conta IS
	PORT(CLK,HAB: IN STD_LOGIC;
	        CUENTA: BUFFER STD_LOGIC_VECTOR(0 TO 3));
END conta;

ARCHITECTURE BEAS OF conta IS
BEGIN

	PROCESS(CLK,HAB)
	  BEGIN 
	     IF FALLING_EDGE (CLK) THEN
			IF HAB = '1' THEN 
				CUENTA<=CUENTA;
		    ELSIF CUENTA="1111" THEN
				CUENTA<="0000";
			ELSE 
				CUENTA<=CUENTA + "0001";
			END IF;
		 END IF;
	END PROCESS;


END BEAS; 